services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - aidocchat_ollama-data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama serve & sleep 10 && ollama pull nomic-embed-text && ollama pull llama3.1:8b && wait"]
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

volumes:
  aidocchat_ollama-data:
    external: true
